Repository HKN-UCSD/hkn-portal, pull requests merged in 2024-04, with the labels that each got.

#146 118 mailing list for event attendees
  frontend/src/Components/Events/CustomizableEventConsole.svelte
Labels: enhancement, priority:low

#145 Add link to profiles from outreach page
  frontend/src/Pages/Inductees.svelte
  frontend/src/Pages/Outreach.svelte
Labels: enhancement, priority:low

#144 Open event description links in new tab
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/Events/EventDetailContent.svelte
Labels: enhancement, priority:low

#151 Feedback hovering button
  frontend/src/App.svelte
  frontend/src/Components/Feedback.svelte
  frontend/src/Layout.svelte
Labels: feature, priority:high

#156 fixed csv file bug
  frontend/src/Pages/Inductees.svelte
  frontend/src/Pages/Outreach.svelte
Labels: bug, priority:medium

#157 152 feature copy rsvp attendees email to clipboard
  frontend/src/Components/Events/CustomizableEventConsole.svelte
Labels: enhancement, priority:low

#155 Feature - Generate QR Code
  frontend/src/Components/Events/CustomizableEventConsole.svelte
  frontend/src/Components/Events/eventutils.js
Labels: enhancement, priority:low

#163 Fix issue with event display caused by previous merges
  frontend/src/Components/Events/CustomizableEventConsole.svelte
  frontend/src/Components/Events/eventutils.js
Labels: bug, priority:high
