Repository HKN-UCSD/hkn-portal, pull requests merged in 2024-03, with the labels that each got.

#141 Change inductee card when on mobile
  frontend/src/Pages/Profile.svelte
Labels: bug, priority:low

#140 Fix edit points bug
  frontend/src/Components/Events/CustomizableEventConsole.svelte
  frontend/src/Components/Events/EditPointsModal.svelte
Labels: bug, priority:high

#139 Implemented add-to-calendar button using Google Calendar API
  frontend/src/Components/Events/CustomizableEventConsole.svelte
  frontend/src/Components/Events/eventutils.js
Labels: feature, priority:low

#122 Device type check, prevent sidebar showing
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/Components/Navbar.svelte
  frontend/src/Components/Sidebar.svelte
  frontend/src/Layout.svelte
  frontend/src/Pages/Events/EventCreate.svelte
  frontend/src/Pages/Events/EventDetail.svelte
  frontend/src/Pages/Events/EventRides.svelte
  frontend/src/Pages/Home.svelte
  frontend/src/Pages/Inductees.svelte
  frontend/src/Pages/Outreach.svelte
  frontend/src/Pages/Profile.svelte
Labels: bug, priority:medium
