Repository HKN-UCSD/hkn-portal, pull requests merged in 2024-05, with the labels that each got.

#147 38 profile page editing
  frontend/src/App.svelte
  frontend/src/Pages/Profile.svelte
  frontend/src/Pages/ProfileEdit.svelte
  myapp/api/views/user_views.py
  package-lock.json
Labels: feature, priority:medium

#166 Bug reduce redundant loading
  frontend/src/App.svelte
  frontend/src/Components/Sidebar.svelte
  frontend/src/Pages/Inductees.svelte
  frontend/src/Pages/Outreach.svelte
  frontend/src/stores.js
  myapp/api/views/user_views.py
Labels: bug

#162 Formatting and code organization; event console updates without reloa…
  frontend/src/Components/Events/CustomizableEventConsole.svelte
  frontend/src/Components/Events/EditPointsModal.svelte
  frontend/src/Components/Events/EventDetailContent.svelte
  frontend/src/Components/Events/eventutils.js
Labels: enhancement, research, priority:low

#169 add pagination + fix filtering
  frontend/src/Components/Icon.svelte
  frontend/src/Components/Pagination.svelte
  frontend/src/Components/SearchBar.svelte
  frontend/src/Components/icon-paths.js
  frontend/src/Pages/Inductees.svelte
  frontend/src/Pages/Outreach.svelte
Labels: bug, feature, priority:low

#161 Added download button for event attendance table
  frontend/src/Components/Events/CustomizableEventConsole.svelte
Labels: enhancement, priority:low
